cacheFolder: .yarn/cache

enableGlobalCache: false

nodeLinker: pnpm

npmScopes:
  marcuzgabriel:
    npmAuthToken: '${GH_TOKEN}'
    npmRegistryServer: 'https://npm.pkg.github.com'

packageExtensions:
  '@storybook/addon-react-native-web@*':
    dependencies:
      webpack: 5.95.0
  '@storybook/core@*':
    dependencies:
      react: 18.3.1
      react-dom: 18.3.1

yarnPath: .yarn/releases/yarn-3.6.4.cjs
