# Inspiration: # inpiratation from https://gist.github.com/belgattitude/042f9caf10d029badbde6cf9d43e400a
name: 'Monorepo install (yarn)'
description: 'Run yarn install with node_modules linker and cache enabled'

runs:
  using: 'composite'

  steps:
    # Get the yarn cache path.
    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      shell: bash
      run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

    # If the provided key matches an existing cache, a new cache is not created and if the provided
    # key doesn't match an existing cache, a new cache is automatically created provided the job completes successfully.
    - name: Restore / save cache
      id: cache
      uses: actions/cache@v4
      with:
        path: |
          node_modules
          packages/*/node_modules
          ${{ steps.yarn-cache-dir-path.outputs.dir }}
        # OS cache key is not needed https://github.com/actions/setup-node/pull/272#issuecomment-873564091.
        # This will reduce the amount of caches that are created and make it more reusable.
        key: yarn-pnpm-cache-${{ hashFiles('**/yarn.lock', '.yarnrc.yml') }}

    # An installation is required everytime to ensure that all local changes are reflected.
    # It is not possible to use the yarn.lock alone to determine if the cache is valid as workspaces
    # may have changed without the yarn.lock file being updated.
    - name: Install dependencies
      shell: bash
      run: yarn install --immutable
