export const DEFAULT_CONFIG = {
  ORIGIN: { x: -10, y: 0 },
  EXPLOSION_SPEED: 350,
  FALL_SPEED: 3500,
  FADE_OUT: false,
  ONLY_SHOW_CUSTOM_SVGS: false,
  BATCH_CONFETTI: false,
  ACTIVATE_ANIMATION: undefined,
  COUNT: 100,
  MIN_SIZE: 20,
  MAX_SIZE: 30,
  DELAY: 0,
  COLORS: ['#48b0f1', '#8fed8f', '#75f3c8', '#fff045', '#f357ac', '#b285fb'],
  SVGS: [],
  CONTAINER_STYLE: {},
};
